name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Windows builds
          - os: windows-latest
            goos: windows
            goarch: amd64
            output: webauto.exe
            archive: webauto-windows-amd64.zip

          # macOS builds
          - os: macos-latest
            goos: darwin
            goarch: amd64
            output: webauto
            archive: webauto-darwin-amd64.tar.gz

          - os: macos-latest
            goos: darwin
            goarch: arm64
            output: webauto
            archive: webauto-darwin-arm64.tar.gz

          # Linux builds
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            output: webauto
            archive: webauto-linux-amd64.tar.gz

          - os: ubuntu-latest
            goos: linux
            goarch: arm64
            output: webauto
            archive: webauto-linux-arm64.tar.gz

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Get version from tag
        id: get_version
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -o ${{ matrix.output }} ./cmd/webauto

      - name: Create archive (Windows)
        if: matrix.goos == 'windows'
        shell: pwsh
        run: |
          Compress-Archive -Path ${{ matrix.output }} -DestinationPath ${{ matrix.archive }}

      - name: Create archive (Unix)
        if: matrix.goos != 'windows'
        run: |
          tar -czf ${{ matrix.archive }} ${{ matrix.output }}

      - name: Calculate SHA256
        id: sha256
        shell: bash
        run: |
          if [ "${{ matrix.goos }}" = "windows" ]; then
            SHA256=$(powershell -Command "(Get-FileHash -Path '${{ matrix.archive }}' -Algorithm SHA256).Hash.ToLower()")
          else
            SHA256=$(shasum -a 256 ${{ matrix.archive }} | awk '{print $1}')
          fi
          echo "SHA256=$SHA256" >> $GITHUB_OUTPUT
          echo "$SHA256  ${{ matrix.archive }}" >> SHA256SUMS-${{ matrix.goos }}-${{ matrix.goarch }}.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            ${{ matrix.archive }}
            SHA256SUMS-${{ matrix.goos }}-${{ matrix.goarch }}.txt

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Merge SHA256 files
        run: |
          find artifacts -name "SHA256SUMS-*.txt" -exec cat {} \; > SHA256SUMS.txt
          cat SHA256SUMS.txt

      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release Notes
        run: |
          cat > RELEASE_NOTES.md << 'EOF'
          ## webauto v${{ steps.get_version.outputs.VERSION }}

          Browser automation plugin for OA CLI with Playwright integration.

          ### Installation

          ```bash
          # Using OA CLI (recommended)
          oa plugin install webauto

          # Manual installation
          # 1. Download the archive for your platform
          # 2. Extract the binary
          # 3. Verify SHA256 checksum
          # 4. Run: oa plugin install ./webauto
          ```

          ### Platform Support

          ✅ **Windows 10/11** (amd64)
          ✅ **macOS 11+** (Intel & Apple Silicon)
          ✅ **Linux Ubuntu 20.04+** (amd64, arm64)

          ### Quick Start

          ```bash
          # Launch browser (Node.js auto-bootstraps on first run)
          oa webauto browser-launch --headless false

          # Navigate to a page
          oa webauto page-navigate --page-url "https://example.com"

          # Take a screenshot
          oa webauto page-screenshot --image-path screenshot.png
          ```

          For detailed platform-specific installation instructions, see the [Platform Guide](https://github.com/oa-plugins/webauto/blob/main/docs/platform-guide.md).

          ### Checksums

          See `SHA256SUMS.txt` for all checksums.

          ### Documentation

          - [README](https://github.com/oa-plugins/webauto#readme)
          - [Platform Guide](https://github.com/oa-plugins/webauto/blob/main/docs/platform-guide.md)
          - [Architecture](https://github.com/oa-plugins/webauto/blob/main/ARCHITECTURE.md)
          - [Issue Tracker](https://github.com/oa-plugins/webauto/issues)
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/*/*
            SHA256SUMS.txt
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
